language: python
python:
  - "3.6"
cache: pip

install:
  - virtualenv -p /usr/bin/python3.6 env
  - ls
  - ls env
  - ls env/bin
  - source env/bin/activate
  - pip install -r requirements.txt

script:
  - python -m pytest
  - ls -l

notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always