language: python
python:
  - "3.6"
cache: pip

install:
  - echo "-----------------> install"
  - pip install -r requirements.txt
  - python -m pytest
  - ls -l

jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        - echo "-----------------> job script"
        - ls
        - cp -rf src dist
        - cp -rf ~/virtualenv/python3.6.3/lib/python3.6/site-packages/* dist

before_deploy:
  - echo '-----------------> prepare to deploy'
  - ls
  - cd dist
  - zip -r hello_serverless.zip .

deploy:
  provider: lambda
  access_key_id:
    secure: "vLkkEmNT3eXO2kRm/IFLcDlD6/XUtzuSqKvNHlh+xAh7CBc087ukNUK/1A03ZmouKqKhIe+Id+BN4vjrfH2EoZ3Y+Cs5iUMU6u7sZzx9xZEMZNpMydKhFc3f/b2ROUwspKcMHTuUV5WrEKb/4243pgVxwiOq3VliajGqPtnXkqXiUNDgpwPXr8hfcT0VPZNcye04dms3b0PqlvhAhVXDdOOUjVWVYkKE2etp6eZs8WO7fzv3M0cabWddNZxKetwrDbikRtxVLBHo9vkS3z8YzUdw4E8hf2YNIinikGa++Yckjvw64IACSrMPH+LgOFwj+L9eOcisF1RaqU4zJXEfRR5XgKmv+SgvohLe/okGg73BNahRVj8Uo6qwKgydTD/xsJgjHzSwzDieEe/bW4FDydPvkB+zpLXxNBOSCKDMu9P7BmAHBIQej0WnVkjiHOum2qBjfRpCsjiQOUTanF7uCH5ismdGj2k/f2EnLRlkj8yYepw4IGaIWnE0T6xHADLjW1AdRFQ/4gqm9u6PE+76zwChZILA+MfSq0u2S0XYSAFe2ntR2w/ZBvWtCaz+sZKyCY/aXhBeUtdkFRG1I2v/IZNLO2QQdrmwBNHj5W2zyueaRaSgWvkHv+nUioTx1sJxOiw4njXmNNjV9Cc4vgAvCkCp+O41XlQlJEMk3hJ66ZY="
  secret_access_key:
    secure: "Q7ZguI6NzMbxQ2irgcpmy+pQNHV6EBInEsEyNln9lHbIbVGWRpEoOjfdFTM+QP8I+0UKE5qq78wTbOkdBJ4Q7omv6Ca5P6vkYEvRNootFF6eTWzLlWPE2qj8ysfFaIsYhAyLZ6T5xWqwPNkYaW7Q9PH5kRua70xW3qGeVAmYy5KX13LOxluZStgD9I+3BnAeMVfJVX+IQH/z9IG2crfe26dh58iSEzOHjsz7GrvffuCuT83VYxjg6cP1Z/dDMP4/FJbtSSc36ctTO27k+fJTgiEZMttQgC3ox8W7DvehOLbfqax+cWYQtgkTpTh1Y5LxuF7BMW0Ikvl5oU9g/d1Sl5k2LR3Es77QhnjlkNYQBvjdrm9w3xB7yoRKZjrt48UdUv/ACNjbIRiqnYbj8o27juGptgkFxbnSZ6sVAxGUZWyVwe2lVCqf+qWoJw2rVau4WtxiE8niH7/gzsOydm7eLLRk2+pwiyCjhijK6f7JQypzfhgCEMaAYmFFKh3vOFMSmrW4J5FkH8AiLGkI/5NkLyTj7Ken0QznK32i6252EqKro/ZqIAfkrTw7G6kCdA918XAczX7zgs+iGxx+r6TH5BmEVLkQvTTzE8jmyN0CpzgtCrhoYQctXZ9PTZ32Ls8lmI9Ak5JRYCqBgZ3nkKgv8PB9QOqSK/X8Sbx8TX/bWus="
  function_name: "$AWSFUNCTIONNAME"
  region: "$AWSREGION"
  role: "arn:aws:iam::$AWSACCOUNTID:role/lambda_basic_execution"
  handler_name: "handler"
  runtime: "python3.6"
  zip_file: "fileb://dist/hello_serverless.zip"


notifications:
  email:
    recipients:
      - inputx@gmail.com
    on_success: change # default: change
    on_failure: always # default: always